### PR TITLE
doc(readme): provide env value to start app

### PR DESCRIPTION
**Pull request by afm-sayem**
Application does not run without providing an environment value

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I'm not sure why that would be. There's always a fallback to dev automatically and I haven't had any trouble running it. Can you provide some more information?

**Comment by afm-sayem** [comment]
Here's what I get without providing environment value.

<pre>
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
{ uid: 7,
  name: 'configureEnvironment',
  branch: false,
  error: 
   { Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
       at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
       at Glob.g (events.js:291:16)
       at emitOne (events.js:96:13)
       at Glob.emit (events.js:188:7)
       at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
       at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
       at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
       at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
       at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
       at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
     domainEmitter: 
      DestroyableTransform {
        _readableState: [Object],
        readable: true,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 35197928 ],
  time: 1478323763812 }
{ uid: 4,
  name: '<series>',
  branch: true,
  error: 
   { Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
       at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
       at Glob.g (events.js:291:16)
       at emitOne (events.js:96:13)
       at Glob.emit (events.js:188:7)
       at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
       at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
       at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
       at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
       at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
       at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
     domainEmitter: 
      DestroyableTransform {
        _readableState: [Object],
        readable: true,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 53844558 ],
  time: 1478323763830 }
{ uid: 3,
  name: '<parallel>',
  branch: true,
  error: 
   { Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
       at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
       at Glob.g (events.js:291:16)
       at emitOne (events.js:96:13)
       at Glob.emit (events.js:188:7)
       at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
       at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
       at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
       at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
       at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
       at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
     domainEmitter: 
      DestroyableTransform {
        _readableState: [Object],
        readable: true,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 59198104 ],
  time: 1478323763835 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: 
   { Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
       at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
       at Glob.g (events.js:291:16)
       at emitOne (events.js:96:13)
       at Glob.emit (events.js:188:7)
       at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
       at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
       at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
       at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
       at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
       at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
     domainEmitter: 
      DestroyableTransform {
        _readableState: [Object],
        readable: true,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 187923617 ],
  time: 1478323763842 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
       at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
       at Glob.g (events.js:291:16)
       at emitOne (events.js:96:13)
       at Glob.emit (events.js:188:7)
       at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
       at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
       at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
       at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
       at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
       at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
     domainEmitter: 
      DestroyableTransform {
        _readableState: [Object],
        readable: true,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function] },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 196324227 ],
  time: 1478323763848 }
{ Error: File not found with singular glob: /home/kishan/projects/opensource/aurelia-ux/aurelia_project/environments/development.ts
    at Glob.<anonymous> (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/index.js:41:11)
    at Glob.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/home/kishan/projects/opensource/aurelia-ux/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
  domainEmitter: 
   DestroyableTransform {
     _readableState: 
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     _events: { end: [Object], prefinish: [Object], data: [Function: ondata] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState: 
      TransformState {
        afterTransform: [Function],
        needTransform: true,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: null },
     _destroyed: false,
     _transform: [Function] },
  domain: 
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [] },
  domainThrown: false }
</pre>

**Comment by egeland** [comment]
Works fine for me, without supplying the `--env dev`...

**Comment by EisenbergEffect** [comment]
I think that in this case @afm-sayem has a local environment variable that is being picked up, overriding the CLI default, and causing the build system to look for a file that doesn't exist.

**Comment by EisenbergEffect** [comment]
I merged this since it will hep ensure that someone with a similar setup won't hit this issue.

**Pull request merged**
